// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMn3rXApPyXSWf66aCnU3JOtvbbwkFpug',
    appId: '1:257021282149:web:73971479992b53d9a3838c',
    messagingSenderId: '257021282149',
    projectId: 'pc-fitness',
    authDomain: 'pc-fitness.firebaseapp.com',
    storageBucket: 'pc-fitness.firebasestorage.app',
    measurementId: 'G-9C0HG5SBRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWYchOWlrht0V-LIDM1P3Hluuf1wzSvFM',
    appId: '1:257021282149:android:fb8b96d08fadf23ea3838c',
    messagingSenderId: '257021282149',
    projectId: 'pc-fitness',
    storageBucket: 'pc-fitness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBltpUYFzG5qua7ICrC-IIw2pzn6uJdRk',
    appId: '1:257021282149:ios:ae30108c7793d6ffa3838c',
    messagingSenderId: '257021282149',
    projectId: 'pc-fitness',
    storageBucket: 'pc-fitness.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBltpUYFzG5qua7ICrC-IIw2pzn6uJdRk',
    appId: '1:257021282149:ios:ae30108c7793d6ffa3838c',
    messagingSenderId: '257021282149',
    projectId: 'pc-fitness',
    storageBucket: 'pc-fitness.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMn3rXApPyXSWf66aCnU3JOtvbbwkFpug',
    appId: '1:257021282149:web:cd99fa1eb349baaca3838c',
    messagingSenderId: '257021282149',
    projectId: 'pc-fitness',
    authDomain: 'pc-fitness.firebaseapp.com',
    storageBucket: 'pc-fitness.firebasestorage.app',
    measurementId: 'G-DKRNQFKGV6',
  );

}